//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Backend_NET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transaction_id {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transaction_id() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory_Backend_NET.Resources.Transaction.id", typeof(Transaction_id).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat membatalkan transaksi milik pengguna lain.
        /// </summary>
        internal static string can_not_cancel_other_user_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_other_user_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaksi yang sudah ditolak tidak dapat dibatalkan.
        /// </summary>
        internal static string can_not_cancel_rejected_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_rejected_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membatalkan transaksi tanpa menginputkan catatan.
        /// </summary>
        internal static string can_not_cancel_transaction_with_empty_notes {
            get {
                return ResourceManager.GetString("can_not_cancel_transaction_with_empty_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terjadi error aplikasi. &apos;Creator&apos; tidak terisi.
        /// </summary>
        internal static string creator_is_empty {
            get {
                return ResourceManager.GetString("creator_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected quantity pada posisi &apos;{0}&apos; tidak teriisi.
        /// </summary>
        internal static string expected_quantity_is_not_filled {
            get {
                return ResourceManager.GetString("expected_quantity_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup harus diisi.
        /// </summary>
        internal static string group_id_must_filled {
            get {
                return ResourceManager.GetString("group_id_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat menetapkan transaksi kepada grup pemasok.
        /// </summary>
        internal static string non_admin_can_not_assign_supplier_group {
            get {
                return ResourceManager.GetString("non_admin_can_not_assign_supplier_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah yang disiapkan pada posisi ke-%s harus diisi.
        /// </summary>
        internal static string prepared_quantity_must_filled {
            get {
                return ResourceManager.GetString("prepared_quantity_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membatalkan transaksi berkali-kali.
        /// </summary>
        internal static string transaction_can_not_canceled_twice {
            get {
                return ResourceManager.GetString("transaction_can_not_canceled_twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id barang pada posisi &apos;{0}&apos; tidak terisi.
        /// </summary>
        internal static string transaction_item_product_id_is_not_filled {
            get {
                return ResourceManager.GetString("transaction_item_product_id_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key json transaction items harus tersedia.
        /// </summary>
        internal static string transaction_items_is_null {
            get {
                return ResourceManager.GetString("transaction_items_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setidaknya harus ada 1 barang transaksi yang dipilih.
        /// </summary>
        internal static string transaction_items_must_have_1_item {
            get {
                return ResourceManager.GetString("transaction_items_must_have_1_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waktu transaksi harus diisi.
        /// </summary>
        internal static string transaction_time_must_filled {
            get {
                return ResourceManager.GetString("transaction_time_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipe transaksi harus &quot;IN&quot; atau &quot;OUT&quot;.
        /// </summary>
        internal static string transaction_type_must_be_in_or_out {
            get {
                return ResourceManager.GetString("transaction_type_must_be_in_or_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipe transaksi harus diisi.
        /// </summary>
        internal static string transaction_type_must_filled {
            get {
                return ResourceManager.GetString("transaction_type_must_filled", resourceCulture);
            }
        }
    }
}
