//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Backend_NET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transaction_id {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transaction_id() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory_Backend_NET.Resources.Transaction.id", typeof(Transaction_id).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat menyerahkan transaksi pada user admin.
        /// </summary>
        internal static string admin_can_not_assign_to_other_admin {
            get {
                return ResourceManager.GetString("admin_can_not_assign_to_other_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin tidak boleh mengkonfirmasi transaksi.
        /// </summary>
        internal static string admin_can_not_confirm_transaction {
            get {
                return ResourceManager.GetString("admin_can_not_confirm_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda hanya dapat memperbarui transaksi dengan status &apos;sudah siap&apos;.
        /// </summary>
        internal static string admin_can_only_updated_prepared_transaction {
            get {
                return ResourceManager.GetString("admin_can_only_updated_prepared_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat membatalkan transaksi milik pengguna lain.
        /// </summary>
        internal static string can_not_cancel_other_user_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_other_user_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaksi yang sudah ditolak tidak dapat dibatalkan.
        /// </summary>
        internal static string can_not_cancel_rejected_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_rejected_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membatalkan transaksi tanpa menginputkan catatan.
        /// </summary>
        internal static string can_not_cancel_transaction_with_empty_notes {
            get {
                return ResourceManager.GetString("can_not_cancel_transaction_with_empty_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terjadi error aplikasi. &apos;Creator&apos; tidak terisi.
        /// </summary>
        internal static string creator_is_empty {
            get {
                return ResourceManager.GetString("creator_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected quantity pada posisi &apos;{0}&apos; tidak teriisi.
        /// </summary>
        internal static string expected_quantity_is_not_filled {
            get {
                return ResourceManager.GetString("expected_quantity_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup harus diisi.
        /// </summary>
        internal static string group_id_must_filled {
            get {
                return ResourceManager.GetString("group_id_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup  dengan id &apos;%s&apos; tidak ditemukan..
        /// </summary>
        internal static string group_id_not_found {
            get {
                return ResourceManager.GetString("group_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat menetapkan transaksi kepada grup pemasok.
        /// </summary>
        internal static string non_admin_can_not_assign_supplier_group {
            get {
                return ResourceManager.GetString("non_admin_can_not_assign_supplier_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat mengkonfirmasi transaksi milik pengguna lain.
        /// </summary>
        internal static string non_admin_can_not_confirm_other_user_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_not_confirm_other_user_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat membuat transaksi bertipe &apos;Stock-masuk&apos;.
        /// </summary>
        internal static string non_admin_can_not_create_transaction_of_type_in {
            get {
                return ResourceManager.GetString("non_admin_can_not_create_transaction_of_type_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak berhak untuk menyiapkan sebuah transaksi.
        /// </summary>
        internal static string non_admin_can_not_prepare_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_not_prepare_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak berhak untuk menolak sebuah transaksi.
        /// </summary>
        internal static string non_admin_can_not_reject_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_not_reject_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda hanya dapat mengkonfirmasi transaksi dengan status &apos;sudah siap&apos;.
        /// </summary>
        internal static string non_admin_can_only_confirm_prepared_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_only_confirm_prepared_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak dapat memperbaharui data transaksi milik user lain..
        /// </summary>
        internal static string non_admin_can_only_update_their_own_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_only_update_their_own_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda hanya dapat memperbaharui data transaksi yang statusnya &apos;menunggu&apos;.
        /// </summary>
        internal static string non_admin_can_only_update_waiting_transaction {
            get {
                return ResourceManager.GetString("non_admin_can_only_update_waiting_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda hanya dapat menolak transaksi yang statusnya &apos;menunggu&apos; atau &apos;sudah siap&apos;.
        /// </summary>
        internal static string only_waiting_and_prepared_transaction_can_be_rejected {
            get {
                return ResourceManager.GetString("only_waiting_and_prepared_transaction_can_be_rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanya transaksi dengan status &apos;menungu&apos; bisa disiapkan.
        /// </summary>
        internal static string only_waiting_transaction_can_be_prepared {
            get {
                return ResourceManager.GetString("only_waiting_transaction_can_be_prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah yang disiapkan pada posisi ke-%s harus diisi.
        /// </summary>
        internal static string prepared_quantity_must_filled {
            get {
                return ResourceManager.GetString("prepared_quantity_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catatan tidak boleh kosong ketika anda menolak sebuah transaksi.
        /// </summary>
        internal static string rejection_notes_must_not_be_empty {
            get {
                return ResourceManager.GetString("rejection_notes_must_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membatalkan transaksi berkali-kali.
        /// </summary>
        internal static string transaction_can_not_canceled_twice {
            get {
                return ResourceManager.GetString("transaction_can_not_canceled_twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah yang diharapkan harus lebih dari 0.
        /// </summary>
        internal static string transaction_item_expected_quantity_must_be_positive {
            get {
                return ResourceManager.GetString("transaction_item_expected_quantity_must_be_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah yang disiapkan tidak boleh lebih dari jumlah yang diharapkan.
        /// </summary>
        internal static string transaction_item_prepared_quantity_cant_be_greater_than_expected_quantity {
            get {
                return ResourceManager.GetString("transaction_item_prepared_quantity_cant_be_greater_than_expected_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah yang disiapkan tidak boleh bilangan negatif.
        /// </summary>
        internal static string transaction_item_prepared_quantity_must_not_be_negative {
            get {
                return ResourceManager.GetString("transaction_item_prepared_quantity_must_not_be_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id barang pada posisi &apos;{0}&apos; tidak terisi.
        /// </summary>
        internal static string transaction_item_product_id_is_not_filled {
            get {
                return ResourceManager.GetString("transaction_item_product_id_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key json transaction items harus tersedia.
        /// </summary>
        internal static string transaction_items_is_null {
            get {
                return ResourceManager.GetString("transaction_items_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setidaknya harus ada 1 barang transaksi yang dipilih.
        /// </summary>
        internal static string transaction_items_must_have_1_item {
            get {
                return ResourceManager.GetString("transaction_items_must_have_1_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah item harus sama dengan sebelumnya.
        /// </summary>
        internal static string transaction_items_size_must_be_same {
            get {
                return ResourceManager.GetString("transaction_items_size_must_be_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waktu transaksi harus diisi.
        /// </summary>
        internal static string transaction_time_must_filled {
            get {
                return ResourceManager.GetString("transaction_time_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipe transaksi harus &quot;IN&quot; atau &quot;OUT&quot;.
        /// </summary>
        internal static string transaction_type_must_be_in_or_out {
            get {
                return ResourceManager.GetString("transaction_type_must_be_in_or_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipe transaksi harus diisi.
        /// </summary>
        internal static string transaction_type_must_filled {
            get {
                return ResourceManager.GetString("transaction_type_must_filled", resourceCulture);
            }
        }
    }
}
