//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Backend_NET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transaction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory_Backend_NET.Resources.Transaction", typeof(Transaction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cancel other user transaction.
        /// </summary>
        internal static string can_not_cancel_other_user_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_other_user_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cancel rejected transaction.
        /// </summary>
        internal static string can_not_cancel_rejected_transaction {
            get {
                return ResourceManager.GetString("can_not_cancel_rejected_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cancel transaction with empty notes.
        /// </summary>
        internal static string can_not_cancel_transaction_with_empty_notes {
            get {
                return ResourceManager.GetString("can_not_cancel_transaction_with_empty_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error. &apos;Creator&apos; is not filled.
        /// </summary>
        internal static string creator_is_empty {
            get {
                return ResourceManager.GetString("creator_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected quantity at position &apos;{0}&apos; is not filled.
        /// </summary>
        internal static string expected_quantity_is_not_filled {
            get {
                return ResourceManager.GetString("expected_quantity_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group must be filled.
        /// </summary>
        internal static string group_id_must_filled {
            get {
                return ResourceManager.GetString("group_id_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t assign transaction to supplier group.
        /// </summary>
        internal static string non_admin_can_not_assign_supplier_group {
            get {
                return ResourceManager.GetString("non_admin_can_not_assign_supplier_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared quantity at %s-th position must filled.
        /// </summary>
        internal static string prepared_quantity_must_filled {
            get {
                return ResourceManager.GetString("prepared_quantity_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction can&apos;t canceled multiple times.
        /// </summary>
        internal static string transaction_can_not_canceled_twice {
            get {
                return ResourceManager.GetString("transaction_can_not_canceled_twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product id at position &apos;{0}&apos; is not filled.
        /// </summary>
        internal static string transaction_item_product_id_is_not_filled {
            get {
                return ResourceManager.GetString("transaction_item_product_id_is_not_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction items json key doesn&apos;t exists.
        /// </summary>
        internal static string transaction_items_is_null {
            get {
                return ResourceManager.GetString("transaction_items_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction items must have at least 1 item.
        /// </summary>
        internal static string transaction_items_must_have_1_item {
            get {
                return ResourceManager.GetString("transaction_items_must_have_1_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction time must be filled.
        /// </summary>
        internal static string transaction_time_must_filled {
            get {
                return ResourceManager.GetString("transaction_time_must_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type must be either &quot;IN&quot; or &quot;OUT&quot;.
        /// </summary>
        internal static string transaction_type_must_be_in_or_out {
            get {
                return ResourceManager.GetString("transaction_type_must_be_in_or_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type must be filled.
        /// </summary>
        internal static string transaction_type_must_filled {
            get {
                return ResourceManager.GetString("transaction_type_must_filled", resourceCulture);
            }
        }
    }
}
